=== NotWoods/Fiascomputer/static/deck-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "https://notwoods.github.io/fiascomatic/deck-schema.json",
	"type": "object",
	"title": "Fiascomatic deck",
	"description": "All the possible cards/tables inside a Fiasco deck.",
	"required": ["tables", "title"],
	"properties": {
		"title": {
			"$id": "#/properties/title",
			"type": "string",
			"title": "Set title",
			"description": "Title presented throughout the app",
			"examples": ["News Channel Six"]
		},
		"subtitle": {
			"$id": "#/properties/subtitle",
			"type": "string",
			"title": "Set subtitle",
			"description": "Subtitle displayed under table lists",
			"default": "",
			"examples": ["...AT NEWS CHANNEL SIX"]
		},
		"backgroundColor": {
			"$id": "#/properties/backgroundColor",
			"type": "string",
			"title": "Set background color",
			"description": "Color displayed behind the logo.",
			"pattern": "^#[a-fA-F0-9]{6}$",
			"default": "#4d0000",
			"examples": ["#22689B"]
		},
		"tables": {
			"$id": "#/properties/tables",
			"title": "Deck tables",
			"description": "Splits up the deck into subsections for relationships, needs, locations, and objects.",
			"anyOf": [
				{
					"required": ["location", "need", "object", "relationship"],
					"properties": {
						"location": { "$ref": "./table-schema.json" },
						"need": { "$ref": "./table-schema.json" },
						"object": { "$ref": "./table-schema.json" },
						"relationship": { "$ref": "./table-schema.json" }
					}
				},
				{
					"required": ["locations", "needs", "objects", "relationships"],
					"properties": {
						"locations": { "$ref": "./table-schema.json" },
						"needs": { "$ref": "./table-schema.json" },
						"objects": { "$ref": "./table-schema.json" },
						"relationships": { "$ref": "./table-schema.json" }
					}
				}
			],
			"examples": [
				{
					"relationship": {
						"title": "Relationships...",
						"categories": [
							{
								"name": "ACTION SIX NEWS TEAM",
								"elements": ["Work rivals"]
							},
							{
								"name": "FAMILY",
								"elements": ["Currently married"]
							},
							{
								"name": "FOOLING AROUND",
								"elements": ["“Secret” lovers only to yourselves"]
							},
							{
								"name": "WE’VE GOT HISTORY",
								"elements": ["“I know a secret about you”"]
							}
						]
					},
					"need": {
						"title": "Needs...",
						"categories": [
							{
								"name": "TO GET LAID",
								"elements": ["Constantly"]
							},
							{
								"name": "TO GET FAMOUS",
								"elements": ["By going out with a bang"]
							},
							{
								"name": "TO GET RICH",
								"elements": ["Through a secret I learned at work"]
							}
						]
					},
					"object": {
						"title": "Objects...",
						"categories": [
							{
								"name": "TOOLS OF THE TRADE",
								"elements": ["Sky Chopper Six!"]
							},
							{
								"name": "PROPS",
								"elements": ["High-powered model rocket", "Giant pot of boiling soup"]
							}
						]
					},
					"location": {
						"title": "Locations...",
						"categories": [
							{
								"name": "HARD NEWS",
								"elements": [
									"At the scene of a grisly murder/suicide",
									"In the trailer park just after the tornado hit"
								]
							}
						]
					}
				}
			]
		},
		"score": {
			"type": "string",
			"title": "The Score",
			"description": "Setting for the deck"
		},
		"kickers": {
			"type": "array",
			"title": "Kickers",
			"description": "Feel free to steal one of these options for a Scene to Establish. Think about what you want for your character!",
			"default": [],
			"items": {
				"type": "string"
			}
		},
		"names": {
			"type": "array",
			"title": "Names",
			"description": "Pool of character names to use",
			"default": [],
			"items": {
				"type": "string"
			}
		}
	}
}

=== NotWoods/Fiascomputer/static/bundled/trashfire_2020.json
{
	"$schema": "../deck-schema.json",
	"title": "Trashfire 2020",
	"backgroundColor": "#D03827",
	"score": "2020 was, as all of you know, a bit more of a fiasco than we'd like. Here at BPG HQ, we could think of no better way* to put the year behind us than to make a Fiasco playset full of our shared pandemic-related frustrations. We hope that you enjoy reading it and maybe even playing it with friends in your next Fiasco game!",
	"tables": {
		"relationship": {
			"categories": [
				{
					"name": "FAMILY",
					"elements": [
						"Spouses for now",
						"Ex-partners stuck together for the duration",
						"Family IT specialist and clueless relative",
						"Teacher and student for the duration",
						"The careful one and the other fucking one",
						"Parent and child"
					]
				},
				{
					"name": "NEIGHBORS",
					"elements": ["Used to be friends", "…who don't agree about social distancing"]
				},
				{
					"name": "CRIMINAL",
					"elements": ["“I got masks, you got weed”", "Casual burglars", "Action figure scalpers"]
				},
				{
					"name": "FRIENDS",
					"elements": [
						"who wont judge each other for zooming in pajamas",
						"…in Animal Crossing, anyway"
					]
				},
				{
					"name": "WORK",
					"elements": ["Coworkers who share a secret", "Bosses of each other", "“Essential”"]
				},
				{
					"name": "ROMANCE",
					"elements": ["Lovers of convenience", "One date, back in March"]
				}
			]
		},
		"need": {
			"title": "NEEDS...",
			"categories": [
				{
					"name": "TO GET RICH",
					"elements": [
						"…by offloading 17,000 rolls of toilet paper",
						"By stealing something",
						"By securing book and movie rights",
						"By fabricating a story",
						"By blackmailing the Big Anchorman",
						"By scamming all my co-workers and then skipping town"
					]
				},
				{
					"name": "TO GET OUT",
					"elements": [
						"…of the soul crushing tedium of working at home",
						"…after curfew",
						"…of your tiny apartment",
						"…of your tiny apartment"
					]
				},
				{
					"name": "TO GET LAID",
					"elements": ["Seriously, do we need to add a detail?"]
				},
				{
					"name": "TO GET FREE",
					"elements": ["…of a weird obligation", "Cowboy Man III action figures, mint in box"]
				},
				{
					"name": "TO GET THROUGH",
					"elements": ["2020", "Cowboy Man III, leaving Netflix tomorrow"]
				},
				{
					"name": "TO GET MORE",
					"elements": ["streaming", "human contact"]
				},
				{
					"name": "TO SHARE",
					"elements": ["…your perfectly ordinary cold", "…more characters in Animal Crossing"]
				}
			]
		},
		"object": {
			"title": "OBJECTS...",
			"categories": [
				{
					"name": "WORK",
					"elements": ["Office plant, dead", "713 unread emails"]
				},
				{
					"name": "HOME",
					"elements": ["Sourdough starter, alive", "Chicken Hut takeout order"]
				},
				{
					"name": "HEALTH",
					"elements": ["5000 doses of Russian “vaccine”", "A bucket of cat tranquilizers"]
				},
				{
					"name": "WEALTH",
					"elements": ["A million dollars, if you get to it first"]
				},
				{
					"name": "FRUSTRATING",
					"elements": [
						"Expensive new N95 mask that doesn't fit",
						"That thing your neighbor put in his yard"
					]
				}
			]
		},
		"location": {
			"title": "LOCATIONS...",
			"categories": [
				{
					"name": "WORK",
					"elements": ["Fifty person Zoom call you are leading", "Red Apple grocery Store"]
				},
				{
					"name": "OUTSIDE",
					"elements": [
						"Michelle's Tavern. Also inside, if you don't give a shit.",
						"Aboard a private jet",
						"Paper goods aisle of the grocery store",
						"Scariest place in the world"
					]
				},
				{
					"name": "INSIDE",
					"elements": ["…your own feverish imagination"]
				},
				{
					"name": "HOME",
					"elements": ["…which is also work", "Back of the pantry where no one would ever look"]
				}
			]
		}
	},
	"kickers": [
		"Your character and someone else's are having a socially-distanced conversation outside. What's it about? What's at stake?",
		"Your character and someone else's both see something they shouldn't at the Red Apple grocery store. What is it?",
		"Your character and another who is in your bubble are sharing another tiresome meal together. Who has a plan for some excitement?",
		"Your character and someone else's are playing with literal fire. What brought you to this moment, and what are you planning to burn, or keep from burning?"
	]
}
